#pragma once
#include <windows.h>
#include <iostream>
#include <cstdint>
#include <memory>
#include <vector>
#include <thread>
#include <chrono>
#include <array>
#include <fstream>
#include <istream>
#include <unordered_map>
#include <intrin.h>
#include "utilities/utilities.hpp"
#include "utilities/minhook/minhook.h"
#include "interfaces/interfaces.hpp"
#include "sdk/sdk.hpp"
#include "hooks/hooks.hpp"
#include "math/math.hpp"
#include "utilities/renderer/renderer.hpp"
#include "sdk/math/matrix.hpp"
#include "menu/imgui/imgui.h"
#include "menu/imgui/impl/imgui_impl_dx9.h"
#include "vars/vars.hpp"
#include "utilities/globals.hpp"